# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export BROWSER=firefox
export EDITOR=vim
export HISTCONTROL=ignoredups
export SCONSFLAGS='-Q -j 8'

shopt -s checkwinsize

alias diff='colordiff'
alias iso8601='date --iso-8601=seconds'
alias cert='openssl x509 -noout -text -in'
alias csr='openssl req -noout -text -in'
alias key='openssl rsa -noout -text -in'
alias ..='cd ..'
alias ...='cd ../..'
alias ll='ls -lh --color=auto'
alias cr='cargo run'
alias soundbar='pacmd set-card-profile 0 output:hdmi-stereo-extra1'
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias snap='grim -g "$(slurp)"'
alias lr='ls | sort -R | head -n 15'
alias rnb='toilet --rainbow -f future'
alias mtl='toilet --metal -f future'
alias rnt='toilet --rainbow -f term'


eval "$(starship init bash)"



source /home/mfs/.config/broot/launcher/bash/br
